create table if not exists rs_calc_job (
    id bigint generated by default as identity primary key,
    period_id bigint not null,
    site_id bigint not null,
    status varchar(20) not null default 'queued',
    total_count integer not null default 0,
    done_count integer not null default 0,
    success_count integer not null default 0,
    failed_count integer not null default 0,
    operator_id bigint,
    target_rider_ids json,
    failures json,
    warnings json,
    error_message text,
    started_time timestamptz,
    finished_time timestamptz,
    created_time timestamptz not null default now(),
    updated_time timestamptz,
    deleted bigint not null default 0,
    deleted_time timestamptz
);

create index if not exists ix_rs_calc_job_period_status on rs_calc_job (period_id, status);

create unique index if not exists uq_rs_calc_job_one_active
    on rs_calc_job (period_id)
    where status in ('queued', 'running') and deleted = 0;

do $$
begin
    if to_regclass('public.rs_calc_job') is null then
        return;
    end if;
    comment on table rs_calc_job is '算薪作业表';
    comment on column rs_calc_job.period_id is '结算周期 ID';
    comment on column rs_calc_job.site_id is '站点 ID';
    comment on column rs_calc_job.status is '状态';
    comment on column rs_calc_job.total_count is '目标骑手数';
    comment on column rs_calc_job.done_count is '已处理骑手数';
    comment on column rs_calc_job.success_count is '成功骑手数';
    comment on column rs_calc_job.failed_count is '失败骑手数';
    comment on column rs_calc_job.operator_id is '操作人 ID';
    comment on column rs_calc_job.target_rider_ids is '指定骑手 ID';
    comment on column rs_calc_job.failures is '失败骑手及原因';
    comment on column rs_calc_job.warnings is '告警';
    comment on column rs_calc_job.error_message is '作业级错误';
    comment on column rs_calc_job.started_time is '开始时间';
    comment on column rs_calc_job.finished_time is '结束时间';
end
$$;
